/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyect_mac;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author 50432
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        usuarios.add(new Usuario("Pancho", "1234"));
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTP_traductor = new javax.swing.JTextPane();
        jdlog_CrearUser = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jtf_crearU_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpf_crear_pass = new javax.swing.JPasswordField();
        jbtn_Crear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fondo_crear = new javax.swing.JLabel();
        jp_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpasf_login_contra = new javax.swing.JPasswordField();
        jbtn_login_ingresar = new javax.swing.JButton();
        jtf_login_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        login_fondo = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar1.setForeground(new java.awt.Color(153, 204, 255));
        jToolBar1.setRollover(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/base-de-datos (1) (1).png"))); // NOI18N
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 30));

        jTabbedPane1.setBackground(new java.awt.Color(153, 204, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jTree1.setBackground(new java.awt.Color(255, 255, 255));
        jTree1.setForeground(new java.awt.Color(0, 0, 0));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Database", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(975, 464));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 202, 766, 256));

        jTP_traductor.setBackground(new java.awt.Color(255, 255, 255));
        jTP_traductor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTP_traductorKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTP_traductor);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 770, 196));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 36, 770, 464));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jdlog_CrearUser.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CREAR USER");
        jdlog_CrearUser.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));
        jdlog_CrearUser.getContentPane().add(jtf_crearU_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 280, 30));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ingrese Nombre");
        jdlog_CrearUser.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cree Contraseña");
        jdlog_CrearUser.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));
        jdlog_CrearUser.getContentPane().add(jpf_crear_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 280, 30));

        jbtn_Crear.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_Crear.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jbtn_Crear.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_Crear.setText("Crear");
        jbtn_Crear.setToolTipText("");
        jbtn_Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_CrearMouseClicked(evt);
            }
        });
        jdlog_CrearUser.getContentPane().add(jbtn_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 370, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Microsoft_Access-Logo.-removebg-preview (1) (1) (1).png"))); // NOI18N
        jdlog_CrearUser.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        fondo_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/_af804daf-cef4-4b3f-ab9b-064a8db244d2.jpg"))); // NOI18N
        fondo_crear.setText("Ingrese Nombre");
        jdlog_CrearUser.getContentPane().add(fondo_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_login.setBackground(new java.awt.Color(153, 153, 153));
        jp_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 58)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        jp_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 260, 70));

        jpasf_login_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasf_login_contraActionPerformed(evt);
            }
        });
        jp_login.add(jpasf_login_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 410, 40));

        jbtn_login_ingresar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_login_ingresar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jbtn_login_ingresar.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_login_ingresar.setText("Ingresar");
        jbtn_login_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_login_ingresarMouseClicked(evt);
            }
        });
        jp_login.add(jbtn_login_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 121, 43));
        jp_login.add(jtf_login_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 410, 40));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese Nombre de Usuario");
        jp_login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");
        jp_login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Microsoft_Access-Logo.-removebg-preview (1) (1) (1).png"))); // NOI18N
        jp_login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Crear Cuenta");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jp_login.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, 30));

        login_fondo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        login_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/_d6af1f89-eb22-4f8a-bd1e-1d91e5023017.jpg"))); // NOI18N
        login_fondo.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                login_fondoVetoableChange(evt);
            }
        });
        jp_login.add(login_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_login, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_login_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_login_ingresarMouseClicked
        if (jtf_login_username.getText().equalsIgnoreCase("Pancho") && (jpasf_login_contra.getText()).equalsIgnoreCase("1234")) {
            jtf_login_username.setText("");
            jpasf_login_contra.setText("");
            this.setVisible(false);
            jDialog1.pack();
            jDialog1.setResizable(false);
            jDialog1.setLocationRelativeTo(null);
            jDialog1.setVisible(true);
        }

        for (Usuario ust : usuarios) {
            if (ust.getNombre() != jtf_login_username.getText()) {

                jtf_login_username.setText("");
                jpasf_login_contra.setText("");
                this.setVisible(false);
                jDialog1.pack();
                jDialog1.setResizable(false);
                jDialog1.setLocationRelativeTo(this);
                jDialog1.setVisible(true);
            } else {
                jtf_login_username.setText("");
                jpasf_login_contra.setText("");
                this.setVisible(false);
                jDialog1.pack();
                jDialog1.setResizable(false);
                jDialog1.setLocationRelativeTo(this);
                jDialog1.setVisible(true);
            }
        }


    }//GEN-LAST:event_jbtn_login_ingresarMouseClicked

    private void login_fondoVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_login_fondoVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_login_fondoVetoableChange

    private void jpasf_login_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasf_login_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasf_login_contraActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        abrirCrear();

    }//GEN-LAST:event_jButton1MouseClicked

    private void jbtn_CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_CrearMouseClicked

        try {
            AdminUsuarios adm = new AdminUsuarios("./User.txt");
            adm.cargarArchivo();

            String n, c;

            n = jtf_crearU_nombre.getText();
            c = jpf_crear_pass.getText();

            System.out.println(jtf_login_username);
            Usuario user = new Usuario(n, c);

            usuarios.add(user);
            adm.getUsuario().add(user);
            adm.escribirArchivo();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        /*  jtf_crearU_nombre.setText("");
        jpf_crear_pass.setText("");*/
        jdlog_CrearUser.pack();
        jdlog_CrearUser.setLocationRelativeTo(this);
        jdlog_CrearUser.setModal(false);
        jdlog_CrearUser.setVisible(false);
    }//GEN-LAST:event_jbtn_CrearMouseClicked

    private void jTP_traductorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTP_traductorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            cambiarTP1(jTP_traductor);
            cambiarTP2(jTP_traductor);
            cambiarTP3(jTP_traductor);
            cambiarTP4(jTP_traductor);
            cambiarTP5(jTP_traductor);
            cambiarTP6(jTP_traductor);
            cambiarTP7(jTP_traductor);
            cambiarTP8(jTP_traductor);
            cambiarTP9(jTP_traductor);

        }
    }//GEN-LAST:event_jTP_traductorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // LOS SIGUIENTES METODOS SON TEMPORALES
    public static void cambiarTP1(JTextPane jtxpane) {
        String text = jtxpane.getText();
        String[] words = text.split("\\s+");

        DefaultStyledDocument doc = new DefaultStyledDocument();
        SimpleAttributeSet standard = new SimpleAttributeSet();
        StyleConstants.setForeground(standard, jtxpane.getForeground());

        for (String word : words) {
            if (word.equalsIgnoreCase("CREATETABLE")) {
                SimpleAttributeSet colored = new SimpleAttributeSet();
                StyleConstants.setForeground(colored, java.awt.Color.BLUE);
                try {
                    doc.insertString(doc.getLength(), word.toUpperCase(), colored);
                    doc.insertString(doc.getLength(), " ", standard);

                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    doc.insertString(doc.getLength(), word, standard);
                    doc.insertString(doc.getLength(), " ", standard);
                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
        }

        jtxpane.setDocument(doc);
    }

    public static void cambiarTP2(JTextPane jtxpane) {
        String text = jtxpane.getText();
        String[] words = text.split("\\s+");

        DefaultStyledDocument doc = new DefaultStyledDocument();
        SimpleAttributeSet standard = new SimpleAttributeSet();
        StyleConstants.setForeground(standard, jtxpane.getForeground());

        for (String word : words) {
            if (word.equalsIgnoreCase("INSERTINTO")) {
                SimpleAttributeSet colored = new SimpleAttributeSet();
                StyleConstants.setForeground(colored, java.awt.Color.BLUE);
                try {
                    doc.insertString(doc.getLength(), word.toUpperCase(), colored);
                    doc.insertString(doc.getLength(), " ", standard);
                    

                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    doc.insertString(doc.getLength(), word, standard);
                    doc.insertString(doc.getLength(), " ", standard);
                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
        }

        jtxpane.setDocument(doc);
    }

    public static void cambiarTP3(JTextPane jtxpane) {
        String text = jtxpane.getText();
        String[] words = text.split("\\s+");

        DefaultStyledDocument doc = new DefaultStyledDocument();
        SimpleAttributeSet standard = new SimpleAttributeSet();
        StyleConstants.setForeground(standard, jtxpane.getForeground());

        for (String word : words) {
            if (word.equalsIgnoreCase("SELECT")) {
                SimpleAttributeSet colored = new SimpleAttributeSet();
                StyleConstants.setForeground(colored, java.awt.Color.BLUE);
                try {
                    doc.insertString(doc.getLength(), word.toUpperCase(), colored);
                    doc.insertString(doc.getLength(), " ", standard);

                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    doc.insertString(doc.getLength(), word, standard);
                    doc.insertString(doc.getLength(), " ", standard);
                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
        }

        jtxpane.setDocument(doc);
    }

    public static void cambiarTP4(JTextPane jtxpane) {
        String text = jtxpane.getText();
        String[] words = text.split("\\s+");

        DefaultStyledDocument doc = new DefaultStyledDocument();
        SimpleAttributeSet standard = new SimpleAttributeSet();
        StyleConstants.setForeground(standard, jtxpane.getForeground());

        for (String word : words) {
            if (word.equalsIgnoreCase("FROM")) {
                SimpleAttributeSet colored = new SimpleAttributeSet();
                StyleConstants.setForeground(colored, java.awt.Color.BLUE);
                try {
                    doc.insertString(doc.getLength(), word.toUpperCase(), colored);
                    doc.insertString(doc.getLength(), " ", standard);

                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    doc.insertString(doc.getLength(), word, standard);
                    doc.insertString(doc.getLength(), " ", standard);
                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
        }

        jtxpane.setDocument(doc);
    }

    public static void cambiarTP5(JTextPane jtxpane) {
        String text = jtxpane.getText();
        String[] words = text.split("\\s+");

        DefaultStyledDocument doc = new DefaultStyledDocument();
        SimpleAttributeSet standard = new SimpleAttributeSet();
        StyleConstants.setForeground(standard, jtxpane.getForeground());

        for (String word : words) {
            if (word.equalsIgnoreCase("WHERE")) {
                SimpleAttributeSet colored = new SimpleAttributeSet();
                StyleConstants.setForeground(colored, java.awt.Color.BLUE);
                try {
                    doc.insertString(doc.getLength(), word.toUpperCase(), colored);
                    doc.insertString(doc.getLength(), " ", standard);

                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    doc.insertString(doc.getLength(), word, standard);
                    doc.insertString(doc.getLength(), " ", standard);
                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
        }

        jtxpane.setDocument(doc);
    }

    public static void cambiarTP6(JTextPane jtxpane) {
        String text = jtxpane.getText();
        String[] words = text.split("\\s+");

        DefaultStyledDocument doc = new DefaultStyledDocument();
        SimpleAttributeSet standard = new SimpleAttributeSet();
        StyleConstants.setForeground(standard, jtxpane.getForeground());

        for (String word : words) {
            if (word.equalsIgnoreCase("UPDATE")) {
                SimpleAttributeSet colored = new SimpleAttributeSet();
                StyleConstants.setForeground(colored, java.awt.Color.BLUE);
                try {
                    doc.insertString(doc.getLength(), word.toUpperCase(), colored);
                    doc.insertString(doc.getLength(), " ", standard);

                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    doc.insertString(doc.getLength(), word, standard);
                    doc.insertString(doc.getLength(), " ", standard);
                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
        }

        jtxpane.setDocument(doc);
    }

    public static void cambiarTP7(JTextPane jtxpane) {
        String text = jtxpane.getText();
        String[] words = text.split("\\s+");

        DefaultStyledDocument doc = new DefaultStyledDocument();
        SimpleAttributeSet standard = new SimpleAttributeSet();
        StyleConstants.setForeground(standard, jtxpane.getForeground());

        for (String word : words) {
            if (word.equalsIgnoreCase("DELETEFROM")) {
                SimpleAttributeSet colored = new SimpleAttributeSet();
                StyleConstants.setForeground(colored, java.awt.Color.BLUE);
                try {
                    doc.insertString(doc.getLength(), word.toUpperCase(), colored);
                    doc.insertString(doc.getLength(), " ", standard);

                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    doc.insertString(doc.getLength(), word, standard);
                    doc.insertString(doc.getLength(), " ", standard);
                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
        }

        jtxpane.setDocument(doc);
    }

    public static void cambiarTP8(JTextPane jtxpane) {
        String text = jtxpane.getText();
        String[] words = text.split("\\s+");

        DefaultStyledDocument doc = new DefaultStyledDocument();
        SimpleAttributeSet standard = new SimpleAttributeSet();
        StyleConstants.setForeground(standard, jtxpane.getForeground());

        for (String word : words) {
            if (word.equalsIgnoreCase("TRUNCATETABLE")) {
                SimpleAttributeSet colored = new SimpleAttributeSet();
                StyleConstants.setForeground(colored, java.awt.Color.BLUE);
                try {
                    doc.insertString(doc.getLength(), word.toUpperCase(), colored);
                    doc.insertString(doc.getLength(), " ", standard);

                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    doc.insertString(doc.getLength(), word, standard);
                    doc.insertString(doc.getLength(), " ", standard);
                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
        }

        jtxpane.setDocument(doc);
    }

    public static void cambiarTP9(JTextPane jtxpane) {
        String text = jtxpane.getText();
        String[] words = text.split("\\s+");

        DefaultStyledDocument doc = new DefaultStyledDocument();
        SimpleAttributeSet standard = new SimpleAttributeSet();
        StyleConstants.setForeground(standard, jtxpane.getForeground());

        for (String word : words) {
            if (word.equalsIgnoreCase("DROPTABLE")) {
                SimpleAttributeSet colored = new SimpleAttributeSet();
                StyleConstants.setForeground(colored, java.awt.Color.BLUE);
                try {
                    doc.insertString(doc.getLength(), word.toUpperCase(), colored);
                    doc.insertString(doc.getLength(), " ", standard);

                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    doc.insertString(doc.getLength(), word, standard);
                    doc.insertString(doc.getLength(), " ", standard);
                } catch (BadLocationException e) {
                    e.printStackTrace();
                }
            }
        }

        jtxpane.setDocument(doc);
    }

    private void abrirCrear() {
        jdlog_CrearUser.pack();
        jdlog_CrearUser.setLocationRelativeTo(this);
        jdlog_CrearUser.setModal(true);
        jdlog_CrearUser.setVisible(true);
    }

    private void abrirLogin() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo_crear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTP_traductor;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton jbtn_Crear;
    private javax.swing.JButton jbtn_login_ingresar;
    private javax.swing.JDialog jdlog_CrearUser;
    private javax.swing.JPanel jp_login;
    private javax.swing.JPasswordField jpasf_login_contra;
    private javax.swing.JPasswordField jpf_crear_pass;
    private javax.swing.JTextField jtf_crearU_nombre;
    private javax.swing.JTextField jtf_login_username;
    private javax.swing.JLabel login_fondo;
    // End of variables declaration//GEN-END:variables

    ArrayList<Usuario> usuarios = new ArrayList();

}
